package rekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import rekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.01 20:00:33 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class KissaTest {



  // Generated by ComTest BEGIN
  /** testGetNimi50 */
  @Test
  public void testGetNimi50() {    // Kissa: 50
    Kissa sadepilvi = new Kissa(); 
    sadepilvi.taytaKissaTiedoilla(); 
    { String _l_=sadepilvi.getNimi(),_r_="Kissakaveri Sadepilvi"; if ( !_l_.matches(_r_) ) fail("From: Kissa line: 53" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi158 */
  @Test
  public void testRekisteroi158() {    // Kissa: 158
    Kissa sadepilvi1 = new Kissa(); 
    assertEquals("From: Kissa line: 160", 0, sadepilvi1.getKissanTunnusNro()); 
    sadepilvi1.rekisteroi(); 
    Kissa sadepilvi2 = new Kissa(); 
    sadepilvi2.rekisteroi(); 
    int n1 = sadepilvi1.getKissanTunnusNro(); 
    int n2 = sadepilvi2.getKissanTunnusNro(); 
    assertEquals("From: Kissa line: 166", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString209 */
  @Test
  public void testToString209() {    // Kissa: 209
    Kissa kissa = new Kissa(); 
    kissa.parse("   1  |  1  | Kissakaveri Sadepilvi"); 
    assertEquals("From: Kissa line: 212", true, kissa.toString().startsWith("1|1|Kissakaveri Sadepilvi|"));  // on enemmänkin kuin 3 kenttää, siksi loppu |
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse244 */
  @Test
  public void testParse244() {    // Kissa: 244
    Kissa kissa = new Kissa(); 
    kissa.parse("   1  |  1   | Kissakaveri Sadepilvi"); 
    assertEquals("From: Kissa line: 247", 1, kissa.getKissanTunnusNro()); 
    assertEquals("From: Kissa line: 248", true, kissa.toString().startsWith("1|1|Kissakaveri Sadepilvi|"));  // on enemmäkin kuin 3 kenttää, siksi loppu |
    kissa.rekisteroi(); 
    int n = kissa.getKissanTunnusNro(); 
    kissa.parse(""+(n+20));  // Otetaan merkkijonosta vain tunnusnumero
    kissa.rekisteroi();  // ja tarkistetaan että seuraavalla kertaa tulee yhtä isompi
    assertEquals("From: Kissa line: 254", n+20+1, kissa.getKissanTunnusNro()); 
  } // Generated by ComTest END
}