package rekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import rekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.16 14:11:51 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class KissaTest {



  // Generated by ComTest BEGIN
  /** testGetNimi47 */
  @Test
  public void testGetNimi47() {    // Kissa: 47
    Kissa sadepilvi = new Kissa(); 
    sadepilvi.taytaKissaTiedoilla(); 
    { String _l_=sadepilvi.getNimi(),_r_="Kissakaveri Sadepilvi"; if ( !_l_.matches(_r_) ) fail("From: Kissa line: 50" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi155 */
  @Test
  public void testRekisteroi155() {    // Kissa: 155
    Kissa sadepilvi1 = new Kissa(); 
    assertEquals("From: Kissa line: 157", 0, sadepilvi1.getKissanTunnusNro()); 
    sadepilvi1.rekisteroi(); 
    Kissa sadepilvi2 = new Kissa(); 
    sadepilvi2.rekisteroi(); 
    int n1 = sadepilvi1.getKissanTunnusNro(); 
    int n2 = sadepilvi2.getKissanTunnusNro(); 
    assertEquals("From: Kissa line: 163", n2-1, n1); 
  } // Generated by ComTest END
}