package rekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import rekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.16 14:24:20 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class OmistajaTest {



  // Generated by ComTest BEGIN
  /** testGetNimi37 */
  @Test
  public void testGetNimi37() {    // Omistaja: 37
    Omistaja sadepilvinen = new Omistaja(); 
    sadepilvinen.taytaKissanOmistaja(1); 
    { String _l_=sadepilvinen.getNimi(),_r_="Sade Pilvinen.*"; if ( !_l_.matches(_r_) ) fail("From: Omistaja line: 40" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi125 */
  @Test
  public void testRekisteroi125() {    // Omistaja: 125
    Omistaja sadepilvinen = new Omistaja(); 
    assertEquals("From: Omistaja line: 127", 0, sadepilvinen.getOmistajanTunnusNro()); 
    sadepilvinen.rekisteroi(); 
    Omistaja sadepilvinen2 = new Omistaja(); 
    sadepilvinen2.rekisteroi(); 
    int n1 = sadepilvinen.getOmistajanTunnusNro(); 
    int n2 = sadepilvinen2.getOmistajanTunnusNro(); 
    assertEquals("From: Omistaja line: 133", n2-1, n1); 
  } // Generated by ComTest END
}