package rekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import rekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.01 20:00:48 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class OmistajaTest {



  // Generated by ComTest BEGIN
  /** testGetNimi37 */
  @Test
  public void testGetNimi37() {    // Omistaja: 37
    Omistaja sadepilvinen = new Omistaja(); 
    sadepilvinen.taytaKissanOmistaja(1); 
    { String _l_=sadepilvinen.getNimi(),_r_="Sade Pilvinen.*"; if ( !_l_.matches(_r_) ) fail("From: Omistaja line: 40" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi125 */
  @Test
  public void testRekisteroi125() {    // Omistaja: 125
    Omistaja sadepilvinen = new Omistaja(); 
    assertEquals("From: Omistaja line: 127", 0, sadepilvinen.getOmistajanTunnusNro()); 
    sadepilvinen.rekisteroi(); 
    Omistaja sadepilvinen2 = new Omistaja(); 
    sadepilvinen2.rekisteroi(); 
    int n1 = sadepilvinen.getOmistajanTunnusNro(); 
    int n2 = sadepilvinen2.getOmistajanTunnusNro(); 
    assertEquals("From: Omistaja line: 133", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString175 */
  @Test
  public void testToString175() {    // Omistaja: 175
    Omistaja omistaja = new Omistaja(); 
    omistaja.parse("   1  |  Sade Pilvinen  | Pilvitie 2 B 16"); 
    assertEquals("From: Omistaja line: 178", true, omistaja.toString().startsWith("1|Sade Pilvinen|Pilvitie 2 B 16|"));  // on enemmänkin kuin 3 kenttää, siksi loppu |
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse201 */
  @Test
  public void testParse201() {    // Omistaja: 201
    Omistaja omistaja = new Omistaja(); 
    omistaja.parse("   1  |  Sade Pilvinen   | Pilvitie 2 B 16"); 
    assertEquals("From: Omistaja line: 204", 1, omistaja.getOmistajanTunnusNro()); 
    assertEquals("From: Omistaja line: 205", true, omistaja.toString().startsWith("1|Sade Pilvinen|Pilvitie 2 B 16|"));  // on enemmänkin kuin 3 kenttää, siksi loppu |
    omistaja.rekisteroi(); 
    int n = omistaja.getOmistajanTunnusNro(); 
    omistaja.parse(""+(n+20));  // Otetaan merkkijonosta vain tunnusnumero
    omistaja.rekisteroi();  // ja tarkistetaan että seuraavalla kertaa tulee yhtä isompi
    assertEquals("From: Omistaja line: 211", n+20+1, omistaja.getOmistajanTunnusNro()); 
  } // Generated by ComTest END
}