package kanta.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import rekisteri.Omistaja;
import kanta.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.20 23:18:57 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TietueTest {



  // Generated by ComTest BEGIN
  /** testInt16 */
  @Test
  public void testInt16() {    // Tietue: 16
    Omistaja omi = new Omistaja(); 
    assertEquals("From: Tietue line: 19", 8, omi.getKenttia()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testInt28 */
  @Test
  public void testInt28() {    // Tietue: 28
    Omistaja omi = new Omistaja(); 
    assertEquals("From: Tietue line: 30", 1, omi.ekaKentta()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testString40 */
  @Test
  public void testString40() {    // Tietue: 40
    Omistaja omi = new Omistaja(); 
    assertEquals("From: Tietue line: 42", "Katuosoite", omi.getKysymys(2)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testString52 */
  @Test
  public void testString52() {    // Tietue: 52
    Omistaja omi = new Omistaja(); 
    omi.parse("   1   |  Sade Pilvinen  |   Pilvitie 2 B 16 | 97612 | Pilvelä "); 
    assertEquals("From: Tietue line: 55", "1", omi.anna(0)); 
    assertEquals("From: Tietue line: 56", "Sade Pilvinen", omi.anna(1)); 
    assertEquals("From: Tietue line: 57", "Pilvitie 2 B 16", omi.anna(2)); 
    assertEquals("From: Tietue line: 58", "97612", omi.anna(3)); 
    assertEquals("From: Tietue line: 59", "Pilvelä", omi.anna(4)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testString72 */
  @Test
  public void testString72() {    // Tietue: 72
    Omistaja omi = new Omistaja(); 
    assertEquals("From: Tietue line: 74", null, omi.aseta(1,"Muru Metsälä")); 
    assertEquals("From: Tietue line: 75", null, omi.aseta(3,"96514")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testTietue86 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testTietue86() throws CloneNotSupportedException {    // Tietue: 86
    Omistaja omi = new Omistaja(); 
    omi.parse("   1   |  Sade Pilvinen  |   Pilvitie 2 B 16 | 97612 | Pilvelä "); 
    Object kopio = omi.clone(); 
    assertEquals("From: Tietue line: 91", omi.toString(), kopio.toString()); 
    omi.parse("   2   |  Kukka Metsälä  |   Metsäpolku 8  | 26100 | Metsäkylä "); 
    assertEquals("From: Tietue line: 93", false, kopio.toString().equals(omi.toString())); 
    assertEquals("From: Tietue line: 94", true, kopio instanceof Omistaja); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testString104 */
  @Test
  public void testString104() {    // Tietue: 104
    Omistaja omistaja = new Omistaja(); 
    omistaja.parse("   2   |  Kukka Metsälä  |   Metsäpolku 8  | 26100 | Metsäkylä "); 
    { String _l_=omistaja.toString(),_r_="2\\|Kukka Metsälä\\|Metsäpolku 8\\|26100\\|Metsäkylä.*"; if ( !_l_.matches(_r_) ) fail("From: Tietue line: 107" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END
}